# Generated by Django 4.0.6 on 2022-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs_app', '0002_alter_brsbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brsbook',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
